source 'https://github.com/NJHu/NJSpecs.git' # NJ 私有源
source 'https://github.com/CocoaPods/Specs.git' # 公有源

platform :ios, '10.3'

use_frameworks!

target 'NJFAQ_Example' do
  pod 'NJFAQ', :path => '../'

  target 'NJFAQ_Tests' do
    inherit! :search_paths

    
  end
end
